#! /bin/sh

sxhkd &

bspc monitor -d main web code im 5 6

#Border width
bspc config border_width         1

# Border colors
bspc config focused_border_color \#F41BC4
bspc config active_border_color \#F41BC4
bspc config normal_border_color \#9C087B

# Window gap
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='web'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a albert border=off

# Wallpaper
feh --bg-scale /home/ubervison/gdrive/Wallpapers/1484761751877-0.jpg &

# Panel
$HOME/.config/polybar/launch.sh

# compton
compton -b &
