#!/bin/python

import urllib.request, json

city = "Lausanne"
api_key = "d19f51457e6e663595eda4feab7ff6f6"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i, °C" % (info, temp))
